# Generated by Django 4.0.2 on 2022-04-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='csname',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=400)),
                ('place', models.CharField(max_length=400)),
                ('time', models.CharField(max_length=20)),
                ('eby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club', to_field='csname')),
            ],
        ),
    ]
