# Generated by Django 4.0.2 on 2022-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_club_csname_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
