# Generated by Django 4.0.2 on 2022-04-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=400)),
                ('time', models.CharField(max_length=20)),
                ('eby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club', to_field='csname')),
            ],
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=200)),
                ('mposition', models.CharField(max_length=200)),
                ('fclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.club', to_field='csname')),
            ],
        ),
    ]
