# Generated by Django 4.0.2 on 2022-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event_clubmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
